// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfpxoRu-pTb-ujoVilkRef5SJqtyYed0E',
    appId: '1:929658320769:web:e2f6a9134a2fde73765a80',
    messagingSenderId: '929658320769',
    projectId: 'qurio-47cb0',
    authDomain: 'qurio-47cb0.firebaseapp.com',
    storageBucket: 'qurio-47cb0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-4wilOON5TC00fn5N1cdIidQrsDRJb4s',
    appId: '1:929658320769:android:ca03d33b0aba7766765a80',
    messagingSenderId: '929658320769',
    projectId: 'qurio-47cb0',
    storageBucket: 'qurio-47cb0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZ8R0ITyzakTOE15-FYUuoiNPltHx1I94',
    appId: '1:929658320769:ios:20a230840f40f218765a80',
    messagingSenderId: '929658320769',
    projectId: 'qurio-47cb0',
    storageBucket: 'qurio-47cb0.firebasestorage.app',
    iosClientId: '929658320769-nq656h836q4uqt1lhl3hnntjedvui71b.apps.googleusercontent.com',
    iosBundleId: 'com.example.qukio',
  );
}
